version: 2

project_name: chdeployer

release:
  prerelease: auto

builds:
  - binary: chdeployer
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

nfpms:
  - package_name: chdeployer
    maintainer: 'Redpill-Linpro <info@redpill-linpro.com>'
    vendor: Redpill-Linpro
    description: CLI tool to deploy and manage resources in MuleSoft Anypoint Platform
    license: Apache License, Version 2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

dockers_v2:
  - images:
      - "ghcr.io/redpill-linpro/chdeployer"
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Containerfile.goreleaser
